#! /usr/bin/env python


from uweclang import *
# import re
from pprint import pprint


text = open("idioms.txt").read().decode('utf-8')


for line in text.splitlines():

    tagged = tag(line)
    t_out = ' '.join(["{}/{}".format(*t) for t in tagged[0]])
    print(t_out)

# print(tagged)
# pprint(dict(get_tags(tagged)))

# pprint(recombine_tag_parentheticals(parse_tag_parentheticals(tagged)))
