#! /usr/bin/env python


from uweclang import *
from pprint import pprint

tagged = tag('This is a test sentence. This is (possible sequenced) another.')

print(is_punctuation(tagged[0][0]))


sep = parse_tag_parentheticals(tagged)
pprint(sep)
pprint(recombine_tag_parentheticals(sep))


# tok = TaggedToken('Word', 'TG')
# print(tok[0])
# print(tok._asdict()['tag'])


