#! /usr/bin/env python3

import sys
import os
import argparse

import uweclang


def extract_plaintext_from_docx(input_filename, output_filename, verbosity=1):
    xml = uweclang.get_document_xml(input_filename, verbosity=verbosity)
    doc = uweclang.xml_to_plain(xml, verbosity=verbosity)

    # Open file for writing.
    if verbosity >= 2:
        print('  Opening file', os.path.basename(output_filename))

    try:
        out = open(output_filename, 'w')
    except IOError as e:
        print('Output file "{}" '
              'could not be created: {}.'.format(os.path.basename(output_filename),
                                                 e))
        sys.exit(0)


    # Write to file.
    if verbosity >= 2:
        print('  Writing to file',os.path.basename(output_filename))

    try:
        out.write(doc.strip())
    except IOError as e:
        print('Could not write to file {}: {}'.format(os.path.basename(output_filename),
                                                      e))
        sys.exit(0)

    out.close()

    if verbosity >= 1:
        print('Extracted plaintext from '
              '{} into {}'.format(os.path.basename(input_filename),
                                  os.path.basename(output_filename)))


if __name__ == '__main__':

    # Create a command line argument parser based on the BATCH_PARSER template.
    # See uweclang/batch/tools.py for details.
    parser = argparse.ArgumentParser(
        description='Extracts plaintext from docx files',
        parents=[uweclang.BATCH_PARSER])


    # Add extra command line arguments for this script.
    parser.add_argument('-e', '--extensions',
                        nargs='*',
                        default=['.docx'],
                        metavar='ext',
                        dest='ext',
                        help='accepted file extensions for input')

    parser.add_argument('-x', '--o-extension',
                        nargs='?',
                        default='.raw.txt',
                        metavar='oext',
                        dest='oext',
                        help='extension for output file')


    # Parse command line arguments.
    args = parser.parse_args()


    # Set default verbosity.
    if args.verbose is None:
        args.verbose = 1


    # Setup extension checking function.
    args.ext = args.ext
    def is_valid_target(file):
        return os.path.isfile(file) and os.path.splitext(file)[1] in args.ext


    # Select the files to process.
    (files, ignored_files) = uweclang.select_files(args,
                                                   file_selector=is_valid_target)


    # Resolve relative ouput path.
    out_path = os.path.abspath(args.output)


    # Print list of ignored files.
    if args.verbose >= 1:
        for x in ignored_files:
            print("Ignore file:", x)
        print('--- Begin Processing ---')


    # Process the files.
    if args.batch_mode == 'none':
        # Process each file seperately.
        for filename in files:
            name_part = os.path.splitext(os.path.basename(filename))[0]
            extract_plaintext_from_docx(filename,
                                        os.path.join(out_path,
                                                     name_part + args.oext),
                                        verbosity=args.verbose)
    else:
        # Process files in batch mode.
        uweclang.batch_process(extract_plaintext_from_docx,
                               in_files=batch_directories,
                               out_dir=out_path,
                               batch_size=args.batch_size,
                               batch_mode=args.batch_mode,
                               verbosity=args.verbose)

    if args.verbose >= 1:
        print('--- End Processing ---')
