#!/usr/bin/env bash

export PYTHONPATH=.

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "Extracting docx files..."

scripts/extract "Student Corpus/Unprocessed Files/" \
			 -o "Student Corpus/Plain Files/"


# Exit if the last command failed.
if [ $? -ne 0 ]; then { echo "Aborting: 'extract' failed." ; exit 1; } fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "Scrubbing plaintext files..."

scripts/scrub "Student Corpus/Plain Files/"		\
		   -o "Student Corpus/Processed Files/" \
		   --batch-size 4						\
		   --batch-mode divide					\
		   -w .txt


# Exit if the last command failed.
if [ $? -ne 0 ]; then { echo "Aborting: 'scrub' failed." ; exit 1; } fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "Tagging processed files..."

scripts/tag "Student Corpus/Processed Files/" \
		 -o "Student Corpus/Tagged Files/"	  \
		 --recursive


# Exit if the last command failed.
if [ $? -ne 0 ]; then { echo "Aborting: 'tag' failed." ; exit 1; } fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "Done."